name: Mirror to GitLab

on:
  push:
    branches: [ "main" ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "dvorak"
          git config --global user.email "xdvorakf@gmail.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://gitlab.rtsoft.cz/co-hackaton-rtsoft-2024/co-hackaton-2024-project-8.git

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push gitlab --all